[pytest]
addopts = -ra
testpaths = tests
pythonpath = src
filterwarnings =
    ignore:websockets.legacy is deprecated:DeprecationWarning
    ignore:Using `httpx` with `starlette.testclient` is deprecated
